INSERT INTO STUDENT VALUES (
	'rrr23', 
	'theSandIsEverywhere', 
	'https://postimg.org/image/k1mulom33/', 
	'Rey', 
	'', 
	'sandSpeeder', 
	'Freshman', 
	'1942-01-01', 
	'Rural Area', 
	'', 
	'Jakku', 
	'Mechanical Engineering', 
	'Science, Technology, Engineering & Mathematics', 
	'one' ,
	'female', 
	'male', 
	'Jedi', 
	'ISTP' , 
	true, 
	'Scavenger', 
	false, 
	'Engineering Shop', 
	5, 
	'never', 
	'Commons', 
	'', 
	5, 
	'At home', 
	'', 
	's', 
	67,  
	'Unknown',  
	'Originally I thought I'd be content to scavenge and wait for my family to return to Jakku, but now I am plannin on becoming a Jedi. ',  
	'Just over the edge of a major life transition.',  
	'If you are interested, lets talk.');

INSERT INTO STUDENT VALUES (
	'glo67', 
	'imAGeneral', 
	'https://postimg.org/image/k1mulom33/', 
	'Leia', 
	'Organa', 
	'princess', 
	'Senior', 
	'1995-06-06', 
	'Polis Massa', 
	'', 
	'Alderaan', 
	'International Relations', 
	'Humanities', 
	'one' ,
	'female', 
	'male', 
	'Jedi', 
	'ENTJ' , 
	true, 
	'Diplomat', 
	false, 
	'Johnnys', 
	1, 
	'always', 
	'Commons', 
	'', 
	5, 
	'International Relations Lounge', 
	'', 
	'a', 
	59,  
	'Alderaanian',  
	'My calling is to make the world a better place through peaceful means, and where those fail perform further actions as necessary. ',  
	'Let me know if you are interested.',  
	'If you are interested, lets talk.');

INSERT INTO STUDENT VALUES (
	'hsf96', 
	'gunsAndGlory', 
	'https://postimg.org/image/k1mulom33/', 
	'Rey', 
	'', 
	'sandSpeeder', 
	'Senior', 
	'1994-11-16', 
	'Rural Area', 
	'', 
	'Corellia', 
	'Mechanical Engineering', 
	'Science, Technology, Engineering & Mathematics', 
	'one' ,
	'male', 
	'female', 
	'Jedi', 
	'ESTP' , 
	true, 
	'Scavenger', 
	false, 
	'Engineering Shop', 
	5, 
	'never', 
	'Commons', 
	'', 
	5, 
	'At home', 
	'', 
	's', 
	71,  
	'Corellian',  
	'My vocation is basically wherever my ship and Chewie are. ',  
	'Look at this hunk of stud!  You know you want me.',  
	'Hit me up!');

INSERT INTO STUDENT VALUES (
	'fn2187', 
	'notEvil', 
	'https://postimg.org/image/k1mulom33/', 
	'Finn', 
	'2187', 
	'FN-2187', 
	'Freshman', 
	'1992-05-09', 
	'Unknown', 
	'Unknown', 
	'Unknown', 
	'Foreign Relations', 
	'Science, Technology, Engineering & Mathematics', 
	'one' ,
	'male', 
	'female', 
	'None', 
	'ENFP' , 
	true, 
	'Resistance Fighter', 
	false, 
	'Bridge', 
	5, 
	'never', 
	'Knollcrest', 
	'', 
	5, 
	'Johnnys', 
	'', 
	'a', 
	70,  
	'Unknown',  
	'I will control my own destiny.',  
	'Tall, dark, and handsome, and built to boot',  
	'Let's get to know each other!');


INSERT INTO MATCH VALUES ('rrr23', 'fn2187', 'Both Freshmen', 1, 1);

INSERT INTO MESSAGE VALUES (1, CURRENT_TIMESTAMP, 'rrr23', 'fn2187', 'Hello');
INSERT INTO MESSAGE VALUES (2, CURRENT_TIMESTAMP, 'fn2187', 'rrr23', 'Hey!  How are things?');
INSERT INTO MESSAGE VALUES (3, CURRENT_TIMESTAMP, 'rrr23', 'fn2187', 'Things are pretty good');

INSERT INTO DATEDATE VALUES (1, 'rrr23', 'fn2187', true, false, 'Johnnys', 'Eat Lunch', '2016-11-08 12:00:00');
